theme: jekyll-theme-minimal



name: Dmytro Hrianko

description: Back-end developer from Kyiv

avatar: https://github.com/RGBsrs/profile/blob/0ce364e4c6afdf8c68bf88badfc30b97cee56ace/photo_2021-03-04_09-00-35.jpg
